# Generated by Django 3.2.6 on 2021-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_hostelinfo_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelinfo',
            name='hostel_image_url',
            field=models.URLField(blank=True, default=' ', null=True),
        ),
    ]
